### ISSUE TITLE
Closed connection is not detected

### ISSUE THREAD

**Issue by peffis** [mysql-otp/mysql-otp-poolboy#17]
Hi, 

I tried mysql_poolboy and for some reason I ended up with one of the connections to mysql being closed without it being removed or restarted by the pool management. This resulted in failed db requests every time this instance was selected in the pool while the other instances worked obviously. Does mysql_poolboy have problems detecting a closed connection? My assumption was that mysql_poolboy would detect this and remove the closed connection from the pool, or am I wrong? 

The exception I got when the connection was closed was the following: 
** Reason for termination == 
** {{{{badmatch,{error,closed}},
      [{mysql_protocol,prepare,3,[{file,"src/mysql_protocol.erl"},{line,98}]},
       {mysql,handle_call,3,[{file,"src/mysql.erl"},{line,585}]},
       {gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},
       {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},
       {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},
     {gen_server,call,
                 [<0.1350.0>,
                  {param_query,"<actual query has been removed>",
                               [72,133]},
                  infinity]}},
    [{gen_server,call,3,[{file,"gen_server.erl"},{line,212}]},
     {mysql,query_call,2,[{file,"src/mysql.erl"},{line,752}]},
     {poolboy,transaction,3,[{file,"src/poolboy.erl"},{line,76}]},
     {db,handle_cast,2,[{file,"src/db.erl"},{line,55}]},
     {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,615}]},
     {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,681}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}

, where the actual query has been removed right now. On line 55 in db.erl I do mysql_poolboy:query which causes this exception.

**Comment by zuiderkwast** [comment]
Detecting connection closed was a problem in early versions of MySQL/OTP, but it was solved in 2016. This was the issue: https://github.com/mysql-otp/mysql-otp/issues/33

As long as the driver kills itself when the connection is lost, the pool should remove it and create a new worker.

If this still is a problem from time to time, perhaps there is a race condition in the code, e.g. where it switches between `{active, once}` and `{active, false}`. I'm closing it now since nothing was said here for years. Please open it again if you still have this issue!
