### ISSUE TITLE
Rename add_pool OR change what it does

### ISSUE THREAD

**Issue by zuiderkwast** [mysql-otp/mysql-otp-poolboy#5]
add_pool is not the best name for a wrapper for poolboy:child_spec/3. It doesn't actuallly add anything but it just returns a child spec. I think it should be called child_spec/3 and take 3 args just like poolboy:child_spec/3.

Maybe we actually want an application with a supervisor for multiple pools? It doesn't mean people have to use it that way. If we are careful, we can make it possible for people to choose (A) to supervise their own pools or, if they want, (B) application:start(mysql_poolboy) and then add_pool(...) to add a pool to mysql_poolboy's top-level supervisor which would be familiar for Emysql users. It could also be possible start pools from config files on start-up (like in the example for poolboy+pgsql).

To supervise their own pools (A), they wouldn't need to start this application. They just call mysql_poolboy:child_spec/3 from their own supervisor.

**Comment by RaoH** [comment]
Sorry about the late answer, christmas time lead to not being at the computer at all almost.
Hmm, when I just quickly structured the example app, I didn't consider the clumsiness having the settings in the app conf file. Now thinking off it, it shouldn't at all be there at all. It's up to the application using this library to have the configuration one way or the other.

But yes add_pool is a bad name considering what it does and since we are not supervising the pool in this app, then it's kinda bad design. So I agree on just wrapping it with mysql_poolboy:child_spec/3.

But if we should keep it and supervise pools, then perhaps another module for it? Seperating concern and functions?

I do like the idea with multiple config files as you suggest. It's very sleek and would mean that adding more db pools is easy and quick, just a simple restart of the application and it's done.
